### PR TITLE
Fixed Issue #4

### PR DESCRIPTION
**Pull request by Vishusingh16**
Created Product Preview Card Component .

### CODE REVIEW

**Comment by Vishusingh16** [comment]
@ankitmrmishra Please review my pull request  .

**Comment by Vishusingh16** [comment]
Sir,
I have made the necessary changes , now everything is working  fine .
Inside Vishu (Branch )> easy> product preview >my-app , all the necessary
code is present inside that my-app folder

**Comment by Vishusingh16** [comment]
@ankitmrmishra  Inside Vishu (Branch  name  )> easy> product preview >my-app. All the necessary code is inside that.

**Comment by Vishusingh16** [comment]
Inside this my-app the code is there.

**Comment by ankitmrmishra** [comment]
Sorry, I.m closing this PR, there's nothing inside Your folder

**Comment by Vishusingh16** [comment]
Sir what should I do? Please let me know.

**Pull request closed without merging**
