### PR TITLE
Product preview card

### PR DESCRIPTION
**Pull request by Anjali-Git-Hub**
Added the product preview card solution .
 Built with  Semantic HTML5 markup, CSS custom properties, Flexbox .
Added media query for making the page responsive .

desktop-design
mobile-design

I faced problems when adding media queries because I got a little bit confused on this topic. However, after reading some documentation from websites like MDN Docs and W3Schools, it became much clearer. If you're a beginner,  you should learn flexbox and media queries before starting this project, or  you can also learn grid.

### CODE REVIEW

**Comment by ankitmrmishra** [comment]
Great PR, could please write details of your PR in this comment you did. Attach Screen Shots of your Live app and also write what you learnt and what were the challenges you faced while doing it.

> Added the product preview card solution .

**Comment by Anjali-Git-Hub** [comment]
@ankitmrmishra , hey I have included all the information you mentioned.

**Comment by ankitmrmishra** [comment]
Thank You for your contribution. Happy HACKTOBERFEST

**Comment by Anjali-Git-Hub** [comment]
@ankitmrmishra thankyou

**Pull request merged**
